# Generated by Django 4.0.4 on 2022-05-17 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_title', models.CharField(help_text='Mersedes', max_length=255, verbose_name='Бренд')),
                ('slug', models.SlugField(help_text='bmw', max_length=255, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренд',
            },
        ),
        migrations.CreateModel(
            name='DriveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_drive', models.CharField(help_text='Передний', max_length=255, verbose_name='Привод машины')),
            ],
            options={
                'verbose_name': 'Тип привода',
                'verbose_name_plural': 'Типы приводов',
            },
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuels', models.CharField(help_text='Бензин', max_length=100, verbose_name='Тип топлива')),
            ],
            options={
                'verbose_name': 'Тип топлива',
                'verbose_name_plural': 'Типы топлива',
            },
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transmission', models.CharField(max_length=255, verbose_name='Тип коробки передач')),
            ],
            options={
                'verbose_name': 'Тип коробки передач',
                'verbose_name_plural': 'Типы коробок передач',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='GLS 63', max_length=255, verbose_name='Модель машины')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_brand', to='cars.brand', verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Модель машины',
                'verbose_name_plural': 'Модель машин',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_image', models.ImageField(upload_to='car_image/', verbose_name='Фотография автомобиля')),
                ('mileage', models.PositiveBigIntegerField(default=0, help_text='120999', verbose_name='Пробег')),
                ('year', models.PositiveBigIntegerField(default=2000, help_text='2000', verbose_name='Год выпуска')),
                ('color', models.CharField(help_text='Черный', max_length=255, verbose_name='Цвет машины')),
                ('color_interior', models.CharField(help_text='Молочный', max_length=255, verbose_name='Цвет интерьера')),
                ('vin', models.CharField(help_text='JTJHY7AX6H42', max_length=255, verbose_name='VIN номер')),
                ('engine', models.CharField(help_text='V8 4.7', max_length=255, verbose_name='Двигатель')),
                ('price', models.PositiveBigIntegerField(help_text=1200000, verbose_name='Цена')),
                ('new_or_old', models.CharField(choices=[('Старый', 'Старый'), ('Новый', 'Новый')], default='Новый', max_length=255, verbose_name='Состояние машины')),
                ('slug', models.SlugField(max_length=255, verbose_name='Слаг')),
                ('brand', models.ForeignKey(help_text='Mersedes', on_delete=django.db.models.deletion.CASCADE, to='cars.brand', verbose_name='Название машины')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_category', to='categories.category', verbose_name='Тип машины')),
                ('drive_type', models.ForeignKey(help_text='Передний', on_delete=django.db.models.deletion.CASCADE, to='cars.drivetype', verbose_name='Привод машины')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_fuel_type', to='cars.fuel', verbose_name='Тип топлива')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_model', to='cars.carmodel', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
    ]
