# Generated by Django 4.0.4 on 2022-05-26 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_drive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя', max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(help_text=255, max_length=255)),
                ('date', models.DateTimeField()),
                ('crated', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Mashina', to='cars.car')),
            ],
            options={
                'verbose_name': 'Тест драйв',
                'verbose_name_plural': 'Тест Драйвы',
            },
        ),
    ]
